# Generated by Django 5.2.11 on 2026-02-08 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='予約タイトル')),
                ('detail', models.TextField(blank=True, verbose_name='詳細内容')),
                ('start', models.DateTimeField(verbose_name='開始日時')),
                ('end', models.DateTimeField(verbose_name='終了日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='予約者')),
            ],
        ),
    ]
