# Generated by Django 5.2.11 on 2026-02-11 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_reservations', to=settings.AUTH_USER_MODEL, verbose_name='参加者'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
    ]
