"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv # [ステップ] ライブラリを読み込む

# [ステップ] .env ファイルの中身を読み込む
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

BASE_URL = os.getenv("BASE_URL", "http://localhost:8000") #ローカルサーバ用
#BASE_URL = os.getenv("BASE_URL", "https://tapnagoyaka.pythonanywhere.com")  #本番用

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

try:
    from .local_settings import *
    DEBUG = True
    ALLOWED_HOSTS = []

except ImportError:
    DEBUG = False
    from django.core.management.utils import get_random_secret_key
    SECRET_KEY = get_random_secret_key()
    ALLOWED_HOSTS = [".pythonanywhere.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # 追加

    #自作アプリ
    'accounts',
    'booking',
    'nagoyaka',

    # 外部ライブラリ
    'allauth',
    'allauth.account',
    'allauth.socialaccount', # 将来的にSNSログインを使うなら必要
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # --- これを追加 ---
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# [ステップ] ブラウザで画像を表示するためのURLの始まりだよ
STATIC_URL = 'static/'

# [ステップ] これを追加！Djangoに「追加でここも探してね」と教える設定だよ
STATICFILES_DIRS = [
    BASE_DIR / "static", # プロジェクト直下に static を作る場合に備えて
]

# [ステップ] 本番環境などで画像を集める場所だよ
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#以下、追加
AUTH_USER_MODEL = "accounts.User"

SITE_ID = 1  # django.contrib.sites用に追加

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# allauthの設定

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
# [ステップ] ここが重要！Allauthに「usernameというフィールドは無い」と教える
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # モデルで None にしたので、ここも None
# 念のため、ACCOUNT_SIGNUP_FIELDS は以下のように整理してください
# （nickname* は CustomSignupForm で作るので、ここでは書かなくてもOKになります）
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# [ステップ] サインアップ時に自作のフォームを使う設定
ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm',
}


ACCOUNT_CONFIRM_EMAIL_ON_GET = True # 認証リンクをクリックしただけで認証完了させる（便利です）

# [ステップ] ログアウトボタンを押した時に「確認画面」を出さずに即実行する
ACCOUNT_LOGOUT_ON_GET = True

#ACCOUNT_EMAIL_VERIFICATION = 'none'     # 開発中はメール認証をスキップ
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

LOGIN_REDIRECT_URL = '/home/'  # ログイン後の移動先
ACCOUNT_LOGOUT_REDIRECT_URL = '/home/'  # ログアウト後の移動先

# メールサーバー用の設定（プロ仕様）
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
# 先生への通知メールの送信元として使われるアドレス
DEFAULT_FROM_EMAIL = os.getenv("EMAIL_HOST_USER")
# [ステップ] メールの送信元を「システム名 <メアド>」の形にする
DEFAULT_FROM_EMAIL = 'TAP_NAGOYAKA <' + os.getenv("EMAIL_HOST_USER") + '>'
# [ステップ] 登録時のメール確認を「しない」に設定（すぐ使えるようにする）
ACCOUNT_EMAIL_VERIFICATION = 'none'